### ISSUE TITLE
More permissive license

### ISSUE THREAD

**Issue by sinkingsugar** [ubisoft/task-scheduler#12]
Given the nature of the library being very low level. GPL license makes it practically unusable by third parties. Is that intentional somehow?

**Comment by Gerold103** [comment]
@sinkingsugar, thanks for taking an interest in the library! Could you please clarify what exactly you mean as unusable, what makes it so? I believe this license was applied by Ubisoft simply because this is a part of Massgate framework, a very old version of which was released under GPL too: https://github.com/ubisoft/massgate. If you could name a better licence for this library, I could talk to our legal department and see if we can change it.

**Comment by sinkingsugar** [comment]
Sure, @Gerold103 , I simply mean statically linking it with our game engine libraries for example. (Or even dynamically) GPL in that case would have to apply to all of our software stack which is unrealistic. That license is fairly "epidemic" 😅

For such a project MIT or BSD2 would be amazing. I'd love to use it and replace current task pool in fact in our code base 👍 
A more permissive license would also attract way more open source contributors 🙏

**Comment by Gerold103** [comment]
Changed to MIT now.

**Comment by sinkingsugar** [comment]
> Changed to MIT now.

Very good news, thank you!

**Comment by sinkingsugar** [comment]
Btw, Still need to change the license in the header of many source files 😄

**Comment by Gerold103** [comment]
Which files? I dropped it from all of them: https://github.com/ubisoft/task-scheduler/commit/6db3c64525aa1b5da38be01f1e6077d87d4bf1ef. Apparently, it doesn't need to be included into each file. Having one LICENSE file is enough.
